language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - pecl install mongo
    - composer self-update
    - composer install --dev

script:
    - cd $TRAVIS_BUILD_DIR/test
    - phpunit --configuration phpunit.xml.ci
    - cd $TRAVIS_BUILD_DIR
    - ./vendor/squizlabs/php_codesniffer/scripts/phpcs --standard=PSR2 -s -p ./src ./test
