language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1

before_script:
    - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update
    - composer install

script:
    - ./vendor/bin/phpunit
    - ./vendor/squizlabs/php_codesniffer/scripts/phpcs --standard=PSR2 -s -p --extensions=php ./src ./test

after_script:
    - php vendor/bin/coveralls
