language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0

before_script:
    - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update
    - composer install

script:
    - cd $TRAVIS_BUILD_DIR/test
    - phpunit --configuration phpunit.xml.ci
    - cd $TRAVIS_BUILD_DIR
    - ./vendor/squizlabs/php_codesniffer/scripts/phpcs --standard=PSR2 -s -p --extensions=php ./src ./test

after_script:
    - php vendor/bin/coveralls
